import { StyleSheet } from "react-native";

export default StyleSheet.create({
  // container
  container: {
    flex: 1,
    backgroundColor: "#F7F5FC",
    flexDirection: "column",
    height: "100%",
    position: "relative",
  },
  containerContactListBar: {
    height: 50,
    backgroundColor: "#010979",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerTagHr: {
    flexDirection: "row",
    alignItems: "center",
  },
  containerBtnShowHied: {
    height: 50,
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerOlderDetail: {
    backgroundColor: "#FFFFFF",
    flexDirection: "column",
  },
  containerOlderDetailName: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerOlderDetailAge: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerOlderDetailStatus: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerOlderDetailStatusShow: {
    flex: 1,
    borderColor: "#F26E4F",
    borderWidth: 1,
    borderRadius: 50,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerOlderDetailDisease: {
    flex: 3,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "flex-start",
    marginVertical: 20,
  },
  containerOlderDetailDiseaseShow: {
    flex: 1,
    borderColor: "#7F7FA8",
    borderWidth: 1,
    borderRadius: 50,
    justifyContent: "flex-start",
    alignItems: "center",
    marginVertical: 5,
  },
  containerOlderDetailStaff: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginVertical: 15,
  },
  containerHelp: {
    flex: 1,
    flexDirection: "row",
    marginTop: 20,
    alignItems: "center",
  },
  containerFooter: {
    height: 90,
    position: "fixed",
    bottom: "0px",
    left: "0px",
    right: "0px",
  },
  containerBgFooter: {
    flexDirection: "row",
    height: 80,
    margin: 5,
    borderRadius: 50,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    shadowColor: "#010979",
    shadowOpacity: 1,
    shadowRadius: 50,
  },
  containerBrowseImg: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
    marginHorizontal: 30,
  },
  containerImgCamera: {
    width: 55,
    height: 50,
    backgroundColor: "#010979",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  containerOlderList: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    flexDirection: "row",
    borderRadius: 10,
  },
  containerBgOlderList: {
    backgroundColor: "#FFFFFF",
    margin: 5,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  containerImageOlder: {
    flex: 2,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  containerOlderDetailList: {
    flex: 6,
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  containerOlderDetailLine2: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-start",
  },

  // image
  imageMap: {
    height: 280,
    flex: 1,
    resizeMode: "center",
  },
  imageContactIconHead: {
    width: 20,
    height: 20,
    backgroundColor: "#010979",
    resizeMode: "center",
    marginHorizontal: 30,
  },
  tutorial: {
    flex: 1,
    width: 349,
    height: 412,
    resizeMode: "center",
    marginVertical: 30,
  },
  imageOlder: {
    width: 66,
    height: 66,
    resizeMode: "center",
    margin: 10,
  },

  // text
  textContactAll: {
    // fontFamily: 'Prompt',
    color: "#FFFFFF",
    fontStyle: "normal",
    fontSize: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  textAll: {
    flex: 2,
    // fontFamily: 'Prompt',
    color: "#1BC3A2",
    fontStyle: "normal",
    fontSize: 14,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
  },
  textOlderName: {
    flex: 3,
    // fontFamily: 'Prompt',
    color: "#010979",
    fontStyle: "normal",
    fontSize: 14,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 30,
  },
  textBtnHied: {
    // fontFamily: 'Prompt',
    flex: 2,
    color: "#FFFFFF",
    fontSize: 12,
  },
  textBtnShow: {
    // fontFamily: 'Prompt',
    flex: 15,
    color: "#FFFFFF",
    fontSize: 12,
  },
  textOlderDetailNameTitle: {
    // fontFamily: 'Prompt',
    flex: 1,
    color: "#3B3D48",
    fontSize: 16,
    marginLeft: 35,
  },
  textOlderDetailName: {
    // fontFamily: 'Prompt',
    flex: 2,
    color: "#010979",
    fontSize: 16,
  },
  textOlderDetailAgeTitle: {
    // fontFamily: 'Prompt',
    flex: 1,
    color: "#3B3D48",
    fontSize: 16,
    marginLeft: 35,
  },
  textOlderDetailAge: {
    // fontFamily: 'Prompt',
    flex: 2,
    color: "#010979",
    fontSize: 16,
  },
  textOlderDetailStatusTitle: {
    // fontFamily: 'Prompt',
    flex: 0.8,
    color: "#3B3D48",
    fontSize: 16,
    marginLeft: 35,
  },
  textOlderDetailStatus: {
    // fontFamily: 'Prompt',
    flex: 1,
    color: "#F26E4F",
    fontSize: 16,
    padding: 2,
  },
  textOlderDetailDiseaseTitle: {
    // fontFamily: 'Prompt',
    flex: 0.8,
    color: "#3B3D48",
    fontSize: 16,
    marginLeft: 35,
  },
  textOlderDetailDisease: {
    // fontFamily: 'Prompt',
    flex: 1,
    color: "#7F7FA8",
    fontSize: 16,
    padding: 2,
  },
  textOlderDetailStaff: {
    // fontFamily: 'Prompt',
    flex: 2,
    color: "#3B3D48",
    fontSize: 16,
    marginLeft: 35,
  },
  textBtnClose: {
    // fontFamily: 'Prompt',
    flex: 1,
    color: "#FFFFFF",
    fontSize: 26,
  },
  textOlderNameList: {
    flex: 1,
    // fontFamily: 'Prompt',
    color: "#0D0E12",
    fontStyle: "normal",
    fontSize: 22,
    marginVertical: 4,
    paddingLeft: 7,
  },
  textOlderAddressModal_1: {
    flex: 4,
    // fontFamily: 'Prompt',
    color: "#0D0E12",
    fontStyle: "normal",
    fontSize: 14,
    marginVertical: 4,
  },
  textOlderAddressModal_2: {
    flex: 8,
    // fontFamily: 'Prompt',
    color: "#6F63FD",
    fontStyle: "normal",
    fontSize: 14,
    marginVertical: 4,
  },

  //icon
  arrow_right_white: {
    width: 20,
    height: 20,
    backgroundColor: "#010979",
    resizeMode: "center",
    marginHorizontal: 30,
  },
  arrow_d: {
    flex: 1,
    width: 20,
    height: 15,
    resizeMode: "center",
  },
  arrow_u: {
    flex: 1,
    width: 20,
    height: 15,
    resizeMode: "center",
  },
  edit_icon: {
    flex: 1,
    width: 32,
    height: 32,
    resizeMode: "center",
  },
  tel: {
    flex: 1,
    width: 32,
    height: 20,
    resizeMode: "center",
  },
  camera: {
    flex: 1,
    width: 32,
    height: 20,
    resizeMode: "center",
  },
  crosshairs_icon: {
    flex: 2,
    height: 30,
    resizeMode: "center",
    margin: 2,
  },
  pin: {
    width: 20,
    height: 30,
    resizeMode: "center",
    margin: 10,
  },

  // button
  btnShowData: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#7676FF",
    padding: 10,
    marginHorizontal: 30,
    borderRadius: 50,
  },
  btnhideData: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#7F7FA8",
    padding: 10,
    marginHorizontal: 30,
    borderRadius: 50,
  },
  btnTel: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#54D5BB",
    padding: 5,
    marginHorizontal: 30,
    borderRadius: 50,
  },
  btnCallHelp: {
    flex: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#54D5BB",
    padding: 5,
    marginHorizontal: 30,
    borderRadius: 50,
  },
  btnhideTutorial: {
    // flex: 1,
    width: 150,
    height: 53,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "#010979",
    padding: 5,
    marginHorizontal: 30,
    borderRadius: 50,
    shadowColor: "#010979",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  btnCancle: {
    flex: 1,
    width: 150,
    height: 53,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#010979",
    padding: 5,
    marginHorizontal: 10,
    borderRadius: 50,
    shadowColor: "#010979",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  btnSubmit: {
    flex: 1,
    width: 150,
    height: 53,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#6F63FD",
    padding: 5,
    marginHorizontal: 10,
    borderRadius: 50,
    shadowColor: "#010979",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },

  // input
  inputTypeEmergency: {
    width: 350,
    fontSize: 18,
    margin: 12,
    borderWidth: 1,
    color: "#0D0E12",
    borderRadius: 10,
    paddingLeft: 12,
  },
  inputSubject: {
    width: 350,
    fontSize: 18,
    margin: 12,
    borderWidth: 1,
    color: "#0D0E12",
    borderRadius: 10,
    paddingLeft: 12,
  },
  inputDetail: {
    width: 350,
    fontSize: 18,
    margin: 12,
    borderWidth: 1,
    color: "#0D0E12",
    borderRadius: 10,
    paddingLeft: 12,
  },
});
